/**
* Reports.js
*
* @description :: Reports model contains information for all types of reports and will be generated by batch jobs.
 * Report includes students attendance in a period time and amount paid.
* @docs        :: http://sailsjs.org/#!documentation/models
*/

module.exports = {

  attributes: {
    uuid:       {
      type:       'string',
      primaryKey: true,
      required:   true
    },
    clientUID:  'string',
    category:   'string',
    startTime:  'datetime'

  }
};

